# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somediaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_name',
            new_name='business_name',
        ),
    ]
