# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somediaapp', '0002_auto_20161112_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somediaapp.UserProfile'),
        ),
    ]
