# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somediaapp', '0003_auto_20161112_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
