# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somediaapp', '0004_product_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetreply',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='tweetreply',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=64, null=True),
        ),
    ]
