# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somediaapp', '0005_auto_20161113_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreply',
            name='reply',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
